"""Automated kill switches and circuit breakers."""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from src.core.events import CircuitBreakerEvent, EventBus
from src.core.models import PortfolioSnapshot

logger = logging.getLogger(__name__)

DEFAULT_STATE_FILE = "data/circuit_breaker_state.json"
DEFAULT_AUDIT_FILE = "logs/circuit_breaker_audit.log"


class CircuitBreaker:
    """Monitors system health and triggers protective actions."""

    def __init__(self, config: dict[str, Any], event_bus: EventBus) -> None:
        self.config = config.get("circuit_breaker", {})
        self.risk_limits = config.get("limits", {})
        self.event_bus = event_bus
        self._halted = False
        self._halt_reason: Optional[str] = None
        self._halt_action: Optional[str] = None
        self._halted_at: Optional[datetime] = None
        self._halt_details: dict[str, Any] = {}
        self._last_resume_by: Optional[str] = None
        self._last_resume_at: Optional[datetime] = None
        self._size_multiplier = 1.0
        self._consecutive_losses = 0
        self._consecutive_api_errors = 0
        self._last_data_time: Optional[datetime] = None
        self._daily_start_equity: Optional[float] = None
        self._peak_equity: Optional[float] = None
        self._state_path = Path(self.config.get("state_file", DEFAULT_STATE_FILE))
        self._audit_path = Path(self.config.get("audit_file", DEFAULT_AUDIT_FILE))
        self._load_state()

    @property
    def is_halted(self) -> bool:
        return self._halted

    @property
    def size_multiplier(self) -> float:
        return self._size_multiplier

    def get_halt_status(self) -> dict[str, Any]:
        return {
            "halted": self._halted,
            "reason": self._halt_reason,
            "action": self._halt_action,
            "halted_at": self._halted_at.isoformat() if self._halted_at else None,
            "details": self._halt_details,
            "last_resume_by": self._last_resume_by,
            "last_resume_at": self._last_resume_at.isoformat() if self._last_resume_at else None,
            "manual_resume_only": self.config.get("manual_resume_only", True),
        }

    def record_data_received(self) -> None:
        self._last_data_time = datetime.utcnow()

    def record_api_error(self) -> None:
        self._consecutive_api_errors += 1
        max_errors = self.config.get("max_consecutive_api_errors", 10)
        if self._consecutive_api_errors >= max_errors:
            self._set_halted(
                reason="consecutive_api_errors",
                action="halt",
                details={"count": self._consecutive_api_errors},
            )
            self._pending_halt_event = CircuitBreakerEvent(
                reason="consecutive_api_errors",
                action="halt",
                details={"count": self._consecutive_api_errors},
            )
            logger.warning(
                "Circuit breaker: %d consecutive API errors — trading paused (manual resume required)",
                self._consecutive_api_errors,
            )

    def take_pending_event(self) -> Optional[CircuitBreakerEvent]:
        """Return and clear any halt event generated by record_api_error."""
        event = getattr(self, "_pending_halt_event", None)
        self._pending_halt_event = None
        return event

    def record_api_success(self) -> None:
        self._consecutive_api_errors = 0

    def record_trade_result(self, pnl: float) -> None:
        if pnl < 0:
            self._consecutive_losses += 1
            limit = self.config.get("consecutive_loss_limit", 5)
            if self._consecutive_losses >= limit:
                reduction = self.config.get("consecutive_loss_size_reduction", 0.5)
                self._size_multiplier = reduction
                self._create_event("consecutive_losses", "reduce_size", {
                    "count": self._consecutive_losses,
                    "new_multiplier": reduction,
                })
        else:
            self._consecutive_losses = 0
            self._size_multiplier = 1.0

    def check(self, portfolio: PortfolioSnapshot) -> Optional[CircuitBreakerEvent]:
        if self._peak_equity is None or portfolio.equity > self._peak_equity:
            self._peak_equity = portfolio.equity

        if self._daily_start_equity is None:
            self._daily_start_equity = portfolio.equity

        daily_loss_pct = (
            (self._daily_start_equity - portfolio.equity) / self._daily_start_equity * 100
            if self._daily_start_equity > 0
            else 0
        )
        max_daily = self.risk_limits.get("max_daily_loss_pct", 5.0)
        if daily_loss_pct >= max_daily and self.config.get("daily_loss_halt", True):
            return self._create_event("daily_loss_limit", "halt", {
                "daily_loss_pct": daily_loss_pct,
            })

        if self._peak_equity and self._peak_equity > 0:
            drawdown = (self._peak_equity - portfolio.equity) / self._peak_equity * 100
            max_dd = self.risk_limits.get("max_drawdown_pct", 15.0)
            if drawdown >= max_dd and self.config.get("max_drawdown_close_all", True):
                return self._create_event("max_drawdown", "close_all", {
                    "drawdown_pct": drawdown,
                })

        if self._last_data_time:
            timeout = self.config.get("data_feed_timeout_seconds", 300)
            elapsed = (datetime.utcnow() - self._last_data_time).total_seconds()
            if elapsed > timeout:
                return self._create_event("data_feed_failure", "halt", {
                    "seconds_since_data": elapsed,
                })

        return None

    def _set_halted(
        self,
        reason: str,
        action: str,
        details: dict[str, Any],
    ) -> None:
        self._halted = True
        self._halt_reason = reason
        self._halt_action = action
        self._halted_at = datetime.utcnow()
        self._halt_details = details
        self._save_state()
        self._audit(f"HALT reason={reason} action={action} details={details}")

    def _create_event(
        self, reason: str, action: str, details: dict[str, Any]
    ) -> CircuitBreakerEvent:
        if action in ("halt", "close_all"):
            self._set_halted(reason, action, details)
        event = CircuitBreakerEvent(reason=reason, action=action, details=details)
        logger.warning("Circuit breaker triggered: %s -> %s", reason, action)
        return event

    async def trigger_and_publish(
        self, reason: str, action: str, details: dict[str, Any]
    ) -> CircuitBreakerEvent:
        event = self._create_event(reason, action, details)
        await self.event_bus.publish(event)
        return event

    def reset_daily(self) -> None:
        self._daily_start_equity = None
        if not self._halted:
            self._size_multiplier = 1.0

    def refresh_from_disk(self) -> None:
        """Apply external manual resume written by CLI while engine is running."""
        if not self._state_path.exists():
            return

        try:
            data = json.loads(self._state_path.read_text())
        except (json.JSONDecodeError, OSError):
            logger.warning("Failed to read circuit breaker state from %s", self._state_path)
            return

        disk_halted = bool(data.get("halted", False))
        if self._halted and not disk_halted:
            self._halted = False
            self._halt_reason = None
            self._halt_action = None
            self._halted_at = None
            self._halt_details = {}
            self._last_resume_by = data.get("last_resume_by")
            resumed_at = data.get("last_resume_at")
            self._last_resume_at = (
                datetime.fromisoformat(resumed_at) if resumed_at else datetime.utcnow()
            )
            self._consecutive_api_errors = 0
            logger.warning(
                "Circuit breaker manually resumed via external command by %s at %s",
                self._last_resume_by,
                self._last_resume_at.isoformat(),
            )

    _RECOVERABLE_HALT_REASONS = frozenset({
        "exchange_sync_failure",
        "consecutive_api_errors",
        "exchange_error",
        "data_feed_failure",
    })

    def resume_on_connectivity_restore(self, operator: str = "engine_startup") -> bool:
        """Clear a halt caused by transient connectivity/API errors after recovery."""
        if not self._halted:
            return False
        reason = self._halt_reason or ""
        if reason not in self._RECOVERABLE_HALT_REASONS:
            logger.info(
                "Circuit breaker still halted (%s) — not auto-resuming (non-recoverable)",
                reason,
            )
            return False
        return self.manual_resume(operator)

    def manual_resume(self, operator: str) -> bool:
        """Explicit human resume — clears any active halt."""
        if not self._halted:
            return False

        now = datetime.utcnow()
        previous_reason = self._halt_reason
        self._halted = False
        self._halt_reason = None
        self._halt_action = None
        self._halted_at = None
        self._halt_details = {}
        self._last_resume_by = operator
        self._last_resume_at = now
        self._consecutive_api_errors = 0
        self._save_state()

        message = (
            f"RESUME operator={operator} at={now.isoformat()} "
            f"previous_halt_reason={previous_reason}"
        )
        self._audit(message)
        logger.warning(
            "Circuit breaker MANUALLY resumed by %s at %s (was halted: %s)",
            operator,
            now.isoformat(),
            previous_reason,
        )
        return True

    def _load_state(self) -> None:
        if not self._state_path.exists():
            return
        try:
            data = json.loads(self._state_path.read_text())
        except (json.JSONDecodeError, OSError):
            logger.warning("Failed to load circuit breaker state from %s", self._state_path)
            return

        self._halted = bool(data.get("halted", False))
        self._halt_reason = data.get("reason")
        self._halt_action = data.get("action")
        halted_at = data.get("halted_at")
        self._halted_at = datetime.fromisoformat(halted_at) if halted_at else None
        self._halt_details = data.get("details", {})
        self._last_resume_by = data.get("last_resume_by")
        resumed_at = data.get("last_resume_at")
        self._last_resume_at = (
            datetime.fromisoformat(resumed_at) if resumed_at else None
        )

    def _save_state(self) -> None:
        try:
            self._state_path.parent.mkdir(parents=True, exist_ok=True)
            payload = {
                "halted": self._halted,
                "reason": self._halt_reason,
                "action": self._halt_action,
                "halted_at": self._halted_at.isoformat() if self._halted_at else None,
                "details": self._halt_details,
                "last_resume_by": self._last_resume_by,
                "last_resume_at": self._last_resume_at.isoformat() if self._last_resume_at else None,
                "updated_at": datetime.utcnow().isoformat(),
            }
            self._state_path.write_text(json.dumps(payload, indent=2))
        except OSError as exc:
            logger.warning("Failed to save circuit breaker state: %s", exc)

    def _audit(self, message: str) -> None:
        try:
            self._audit_path.parent.mkdir(parents=True, exist_ok=True)
            line = f"{datetime.utcnow().isoformat()} {message}\n"
            with self._audit_path.open("a") as audit_file:
                audit_file.write(line)
        except OSError as exc:
            logger.warning("Failed to write circuit breaker audit log: %s", exc)
